### ISSUE TITLE
Error: Cannot find module './build/Release/shell'

### ISSUE THREAD

**Issue by fridgamarator** [jtomaszewski/ionic-cordova-gulp-seed#6]
```
╰─➤  gulp                                                                                                                                                                                                  127 ↵
module.js:338
    throw err;
          ^
Error: Cannot find module './build/Release/shell'
  at Function.Module._resolveFilename (module.js:336:15)
  at Function.Module._load (module.js:278:25)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Object.<anonymous> (/Users/nick/Sites/ionicstarter-mobile/node_modules/execSync/index.js:30:11)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (/Users/nick/Sites/ionicstarter-mobile/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Object.<anonymous> (/Users/nick/Sites/ionicstarter-mobile/gulp/config.coffee:4:12)
  at Object.<anonymous> (/Users/nick/Sites/ionicstarter-mobile/gulp/config.coffee:1:1)
  at Module._compile (module.js:460:26)
  at Object.loadFile (/Users/nick/Sites/ionicstarter-mobile/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/Users/nick/Sites/ionicstarter-mobile/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Object.<anonymous> (/Users/nick/Sites/ionicstarter-mobile/gulp/main.coffee:2:1)
  at Object.<anonymous> (/Users/nick/Sites/ionicstarter-mobile/gulp/main.coffee:2:1)
  at Module._compile (module.js:460:26)
  at Object.loadFile (/Users/nick/Sites/ionicstarter-mobile/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/Users/nick/Sites/ionicstarter-mobile/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Object.<anonymous> (/Users/nick/Sites/ionicstarter-mobile/gulpfile.js:2:1)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
  at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:181:16)
  at module.exports (/usr/local/lib/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)
  at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:174:9)
  at /usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:148:9
  at /usr/local/lib/node_modules/gulp/node_modules/v8flags/index.js:13:7
  at process._tickCallback (node.js:355:11)
  at Function.Module.runMain (module.js:503:11)
  at startup (node.js:129:16)
  at node.js:814:3
```

**Comment by jtomaszewski** [comment]
Strange. Seems like it would be an issue of execSync - because the error happens in `execSync = require("execSync")` line. 

As I can see on https://github.com/mgutz/execSync , it's deprecated. Propably we should switch to [ShellJS](http://documentup.com/arturadib/shelljs) or [something else](https://strongloop.com/strongblog/whats-new-in-node-js-v0-12-execsync-a-synchronous-api-for-child-processes/).

**Comment by fridgamarator** [comment]
My npm version was a major version out of date.  This is working fine after updating npm.  Sorry!
